-- ----------------------------------------------------------
-- Merged SQL (generated by merge_sql.py)
-- Files merged : 10 / 10
-- Source dir   : i:\Dext-Sever\SQL
-- 导入前请确保当前连接已切换到目标数据库(如: USE your_db;)
-- 保留 CREATE DATABASE / USE 设 MERGE_KEEP_DB_META=1
-- 关闭重置段(不要 DROP)设 MERGE_SKIP_DROP=1
-- ----------------------------------------------------------

-- 0) 重置段: 反向 DROP TABLE IF EXISTS,清掉老残留,确保干净重建。
DROP TABLE IF EXISTS `refresh_tokens`;
DROP TABLE IF EXISTS `oauth_accounts`;
DROP TABLE IF EXISTS `oauth_binding_verifications`;
DROP TABLE IF EXISTS `oauth_bindings`;
DROP TABLE IF EXISTS `email_verifications`;
DROP TABLE IF EXISTS `jwt_blacklist`;
DROP TABLE IF EXISTS `user_sessions`;
DROP TABLE IF EXISTS `oauth_email_history`;
DROP TABLE IF EXISTS `oauth_email_conflicts`;
DROP TABLE IF EXISTS `survey_assets_files`;
DROP TABLE IF EXISTS `survey_submissions`;
DROP TABLE IF EXISTS `survey_views`;
DROP TABLE IF EXISTS `survey_stats`;
DROP TABLE IF EXISTS `answer_details`;
DROP TABLE IF EXISTS `answers`;
DROP TABLE IF EXISTS `question_options`;
DROP TABLE IF EXISTS `questions`;
DROP TABLE IF EXISTS `survey_backgrounds`;
DROP TABLE IF EXISTS `surveys`;
DROP TABLE IF EXISTS `projects`;
DROP TABLE IF EXISTS `users`;

-- ----------------------------------------------------------------------
-- >>> Source: database_schema.sql
-- ----------------------------------------------------------------------

-- OpenAssets Database Complete Structure
-- Create database


-- Users table
CREATE TABLE IF NOT EXISTS users (
    id VARCHAR(64) PRIMARY KEY,
    username VARCHAR(12) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE COMMENT 'User email',
    avatar_url VARCHAR(500),
    -- 显示名 / 昵称,原本在 _migrations/add_oauth_support.sql 单独
    -- ALTER 加过,新装库漏跑会 1054。直接进 CREATE TABLE。
    display_name VARCHAR(255) DEFAULT NULL COMMENT 'Display name',
    user_role INT DEFAULT 0,
    failed_attempts INT DEFAULT 0,
    locked_until DATETIME,
    -- 邮箱验证状态,add_email_verification.sql 会 ALTER 加,这里直接建好
    -- 以便全库一次到位、避免 1054。
    email_verified BOOLEAN DEFAULT FALSE COMMENT 'Whether email is verified',
    email_verified_at DATETIME NULL COMMENT 'Email verification time',
    -- 逻辑删除,add_users_logical_delete.sql 会 ALTER 加。
    is_delete TINYINT NOT NULL DEFAULT 0 COMMENT 'Logical delete: 0-Not deleted, 1-Deleted',
    deleted_at TIMESTAMP NULL DEFAULT NULL COMMENT 'Deletion timestamp',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_email (email),
    INDEX idx_users_is_delete (is_delete),
    INDEX idx_users_deleted_at (deleted_at),
    INDEX idx_users_email_verified (email_verified)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- OAuth user ID fix patch - 2025/10/06
-- Ensure OAuth users can be stored and queried correctly
UPDATE users SET id = CONCAT('oauth_', UNIX_TIMESTAMP(), '_', SUBSTRING(MD5(email), 1, 8)) 
WHERE email LIKE '%@%' AND LENGTH(id) < 10;

-- Projects table
CREATE TABLE IF NOT EXISTS projects (
    id INT PRIMARY KEY AUTO_INCREMENT,
    project_name VARCHAR(100) NOT NULL,
    project_description TEXT,
    user_id VARCHAR(64) NOT NULL,
    create_by VARCHAR(12) NOT NULL,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    update_by VARCHAR(12) NOT NULL,
    INDEX idx_user_id (user_id),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Surveys table
CREATE TABLE IF NOT EXISTS surveys (
    id INT PRIMARY KEY AUTO_INCREMENT,
    survey_uid VARCHAR(64) NOT NULL UNIQUE,
    survey_name VARCHAR(100) NOT NULL,
    description TEXT,
    survey_type INT NOT NULL,
    survey_status INT DEFAULT 0,
    total_times INT DEFAULT 0,
    per_user_limit INT NULL DEFAULT NULL,
    project_id INT NOT NULL,
    deadline DATETIME NULL,
    -- 选完自动提交 / 允许匿名提交,原本在 add_survey_features.sql 里
    -- 单独 ALTER 加的,新装库容易漏。直接写进 CREATE TABLE 避免 1054。
    auto_submit BOOLEAN DEFAULT FALSE COMMENT 'Enable automatic submission when all questions are answered',
    allow_anonymous BOOLEAN DEFAULT FALSE COMMENT 'Allow anonymous users to submit without login',
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_project_id (project_id),
    FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Survey backgrounds table
CREATE TABLE IF NOT EXISTS survey_backgrounds (
    id INT AUTO_INCREMENT PRIMARY KEY,
    survey_id INT NOT NULL,
    desktop_background TEXT,
    mobile_background TEXT,
    created_by VARCHAR(50) NOT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    FOREIGN KEY (survey_id) REFERENCES surveys(id) ON DELETE CASCADE,
    UNIQUE KEY unique_survey_background (survey_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


-- Questions table
CREATE TABLE IF NOT EXISTS questions (
    id INT PRIMARY KEY AUTO_INCREMENT,
    survey_id INT NOT NULL,
    question_type INT NOT NULL,
    question_description TEXT NOT NULL,
    question_order INT DEFAULT 0,
    is_required BOOLEAN DEFAULT TRUE,
    media_urls JSON,
    jump_logic JSON,
    -- 图片缩放系数,原本在 add_image_scale_column.sql 单独 ALTER 加,
    -- 新装库漏跑会 1054。直接进 CREATE TABLE。
    image_scale DECIMAL(3,2) NOT NULL DEFAULT 1.00 COMMENT 'Image display scale factor (0.5-2.0)',
    INDEX idx_survey_id (survey_id),
    FOREIGN KEY (survey_id) REFERENCES surveys(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Question options table
CREATE TABLE IF NOT EXISTS question_options (
    id INT PRIMARY KEY AUTO_INCREMENT,
    question_id INT NOT NULL,
    option_text TEXT NOT NULL,
    option_order INT DEFAULT 0,
    media_url VARCHAR(500),
    -- 跳转目标问题 ID:NULL=默认下一题,-1=结束问卷。原本 DEFAULT 0 不允许
    -- NULL/负值,fix_destination_column.sql 单独改过,新装库直接建成可空。
    destination_question_id INT NULL DEFAULT NULL COMMENT 'Jump target question ID; -1=end survey; NULL=default next',
    -- 自定义输入占位符,原本在 add_custom_input_placeholder.sql 单独 ALTER 加,
    -- 新装库漏跑会 1054。直接进 CREATE TABLE。
    custom_input_placeholder VARCHAR(200) DEFAULT NULL COMMENT 'Placeholder text for custom input options',
    INDEX idx_question_id (question_id),
    FOREIGN KEY (question_id) REFERENCES questions(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Answers table
CREATE TABLE IF NOT EXISTS answers (
    id INT PRIMARY KEY AUTO_INCREMENT,
    survey_id INT NOT NULL,
    user_id VARCHAR(64) NOT NULL,
    user_account VARCHAR(12) NOT NULL,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    -- 逻辑删除标记:0-未删,1-已删。原本在 add_history_logical_delete.sql
    -- 单独 ALTER 加,新装库漏跑会 1054。直接进 CREATE TABLE。
    is_delete TINYINT NOT NULL DEFAULT 0 COMMENT 'Logical delete: 0-Not deleted, 1-Deleted',
    deleted_at TIMESTAMP NULL DEFAULT NULL COMMENT 'Deletion timestamp (paired with is_delete)',
    INDEX idx_survey_id (survey_id),
    INDEX idx_user_id (user_id),
    INDEX idx_answers_is_delete (is_delete),
    INDEX idx_answers_deleted_at (deleted_at),
    FOREIGN KEY (survey_id) REFERENCES surveys(id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Answer details table
CREATE TABLE IF NOT EXISTS answer_details (
    id INT PRIMARY KEY AUTO_INCREMENT,
    answer_id INT NOT NULL,
    question_id INT NOT NULL,
    selected_options JSON NOT NULL,
    INDEX idx_answer_id (answer_id),
    INDEX idx_question_id (question_id),
    FOREIGN KEY (answer_id) REFERENCES answers(id) ON DELETE CASCADE,
    FOREIGN KEY (question_id) REFERENCES questions(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Survey statistics table
CREATE TABLE IF NOT EXISTS survey_stats (
    survey_id INT PRIMARY KEY,
    view_count INT DEFAULT 0,
    submit_count INT DEFAULT 0,
    last_view_time TIMESTAMP NULL DEFAULT NULL,
    last_submit_time TIMESTAMP NULL DEFAULT NULL,
    FOREIGN KEY (survey_id) REFERENCES surveys(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Survey views table
CREATE TABLE IF NOT EXISTS survey_views (
    id INT AUTO_INCREMENT PRIMARY KEY,
    survey_id INT,
    view_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    viewer_ip VARCHAR(45),
    INDEX idx_survey_id (survey_id),
    INDEX idx_view_time (view_time),
    INDEX idx_survey_view_time (survey_id, view_time),
    FOREIGN KEY (survey_id) REFERENCES surveys(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Survey submissions table
CREATE TABLE IF NOT EXISTS survey_submissions (
    id INT AUTO_INCREMENT PRIMARY KEY,
    survey_id INT,
    user_id VARCHAR(64),
    submit_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_survey_id (survey_id),
    INDEX idx_user_id (user_id),
    INDEX idx_submit_time (submit_time),
    INDEX idx_survey_submit_time (survey_id, submit_time),
    FOREIGN KEY (survey_id) REFERENCES surveys(id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Survey assets files table
CREATE TABLE IF NOT EXISTS survey_assets_files (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    survey_id INT NOT NULL,
    username VARCHAR(50) NOT NULL,
    file_name VARCHAR(255) NOT NULL,
    file_url TEXT NOT NULL,
    file_size BIGINT NOT NULL,
    content_type VARCHAR(100) NOT NULL,
    upload_time DATETIME NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    
    -- Indexes
    INDEX idx_survey_id (survey_id),
    INDEX idx_username (username),
    INDEX idx_upload_time (upload_time),
    INDEX idx_file_name (file_name),
    
    -- Foreign key constraints
    FOREIGN KEY (survey_id) REFERENCES surveys(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;



-- Create additional indexes
-- 注意: idx_survey_uid / idx_users_username / idx_survey_backgrounds_survey_id
-- 等已由对应列的 inline UNIQUE 提供约束,这里不再重复 CREATE INDEX,
-- 否则在已有残留索引的库上会报 Duplicate key name。
CREATE INDEX idx_projects_create_by ON projects(create_by);
CREATE INDEX idx_projects_create_by_id ON projects(create_by, id);
CREATE INDEX idx_surveys_project_id_comp ON surveys(project_id, id);

-- Add indexes for query performance enhancement
CREATE INDEX idx_survey_backgrounds_created_by ON survey_backgrounds(created_by);


-- Add table comments
ALTER TABLE users COMMENT = 'Users table - Store user account information';
ALTER TABLE projects COMMENT = 'Projects table - Store user created projects';
ALTER TABLE surveys COMMENT = 'Surveys table - Store survey basic information';
ALTER TABLE questions COMMENT = 'Questions table - Store questions in surveys';
ALTER TABLE question_options COMMENT = 'Question options table - Store question options';
ALTER TABLE answers COMMENT = 'Answers table - Store user submitted answers';
ALTER TABLE answer_details COMMENT = 'Answer details table - Store answer specific options (JSON: {"texts":[], "indices":[]})';
ALTER TABLE survey_stats COMMENT = 'Survey statistics table - Store survey access and submission statistics';
ALTER TABLE survey_views COMMENT = 'Survey views table - Record survey access information';
ALTER TABLE survey_submissions COMMENT = 'Survey submissions table - Record survey submission information';
ALTER TABLE survey_assets_files COMMENT = 'Survey assets files table - Store survey related assets files';


-- Insert default admin user (optional)
-- INSERT INTO users (id, username, password_hash, user_role) VALUES 
-- ('admin_001', 'admin', '$2a$12$LQv3c1yqBWVHxkd0LHAkCOYz6TtxMQJqhN8/LewdBPj/RK.s5u.Ge', 1);
-- Note: The password hash above needs to be generated according to actual requirements
-- 末尾的 SHOW TABLES / information_schema 查询语句已移除(便于无差异导入)

-- ----------------------------------------------------------------------
-- >>> Source: create_oauth_email_conflicts_table.sql
-- ----------------------------------------------------------------------

-- Create oauth_email_conflicts table for tracking OAuth email conflicts
CREATE TABLE IF NOT EXISTS oauth_email_conflicts (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id VARCHAR(64) NOT NULL COMMENT 'User ID experiencing the conflict',
    provider VARCHAR(32) NOT NULL COMMENT 'OAuth provider (google, github, microsoft)',
    old_email VARCHAR(255) COMMENT 'Previous email address',
    new_email VARCHAR(255) NOT NULL COMMENT 'New email address causing conflict',
    conflict_user_id VARCHAR(64) COMMENT 'ID of user who already has this email',
    conflict_type ENUM('email_occupied', 'binding_conflict', 'provider_change') NOT NULL COMMENT 'Type of conflict',
    resolution_status ENUM('pending', 'resolved', 'ignored') DEFAULT 'pending' COMMENT 'Status of conflict resolution',
    resolution_method VARCHAR(50) COMMENT 'Method used to resolve conflict',
    notes TEXT COMMENT 'Additional notes about the conflict',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT 'When conflict was detected',
    resolved_at TIMESTAMP NULL COMMENT 'When conflict was resolved',
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    
    -- Indexes for performance
    INDEX idx_user_id (user_id),
    INDEX idx_provider (provider),
    INDEX idx_new_email (new_email),
    INDEX idx_conflict_user_id (conflict_user_id),
    INDEX idx_resolution_status (resolution_status),
    INDEX idx_created_at (created_at),
    
    -- Composite indexes for common queries
    INDEX idx_user_provider (user_id, provider),
    INDEX idx_status_created (resolution_status, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='OAuth email conflicts tracking table';

-- Create oauth_email_history table for tracking email changes
CREATE TABLE IF NOT EXISTS oauth_email_history (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id VARCHAR(64) NOT NULL COMMENT 'User ID',
    provider VARCHAR(32) NOT NULL COMMENT 'OAuth provider',
    old_email VARCHAR(255) COMMENT 'Previous email',
    new_email VARCHAR(255) NOT NULL COMMENT 'New email',
    change_reason VARCHAR(100) COMMENT 'Reason for email change',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT 'When change occurred',
    
    -- Indexes
    INDEX idx_user_id (user_id),
    INDEX idx_provider (provider),
    INDEX idx_user_provider (user_id, provider),
    INDEX idx_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='OAuth email change history table';

-- Show created tables
SELECT 'oauth_email_conflicts table created successfully' as status;
SELECT 'oauth_email_history table created successfully' as status;

-- ----------------------------------------------------------------------
-- >>> Source: create_session_tables.sql
-- ----------------------------------------------------------------------

-- Create session tables with UTF-8 encoding
CREATE TABLE IF NOT EXISTS user_sessions (
    id VARCHAR(64) PRIMARY KEY,
    user_id VARCHAR(64) NOT NULL,
    token_hash VARCHAR(255) NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_accessed TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    ip_address VARCHAR(45),
    user_agent TEXT,
    is_active BOOLEAN DEFAULT TRUE,
    INDEX idx_user_id (user_id),
    INDEX idx_expires (expires_at),
    INDEX idx_token_hash (token_hash),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS jwt_blacklist (
    id INT PRIMARY KEY AUTO_INCREMENT,
    token_hash VARCHAR(255) UNIQUE NOT NULL,
    user_id VARCHAR(64),
    expires_at TIMESTAMP NOT NULL,
    revoked_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    reason VARCHAR(100) DEFAULT 'manual_logout',
    INDEX idx_token_hash (token_hash),
    INDEX idx_expires (expires_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ----------------------------------------------------------------------
-- >>> Source: add_email_verification.sql
-- ----------------------------------------------------------------------

-- Email verification code table
-- Store email verification codes for registration, password reset, and email change scenarios

CREATE TABLE IF NOT EXISTS email_verifications (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(255) NOT NULL COMMENT 'Target email address',
    code VARCHAR(6) NOT NULL COMMENT '6-digit verification code',
    purpose ENUM('register', 'reset_password', 'change_email', 'delete_account') NOT NULL COMMENT 'Verification purpose',
    user_id VARCHAR(64) NULL COMMENT 'Associated user ID (for password reset/email change)',
    verified BOOLEAN DEFAULT FALSE COMMENT 'Whether verified',
    expires_at DATETIME NOT NULL COMMENT 'Expiration time',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT 'Creation time',
    verified_at DATETIME NULL COMMENT 'Verification time',
    
    INDEX idx_email (email),
    INDEX idx_code (code),
    INDEX idx_expires_at (expires_at),
    INDEX idx_email_purpose (email, purpose),
    INDEX idx_user_id (user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Email verification code table';

-- users.email_verified / email_verified_at 已在 database_schema.sql 中,
-- 此前的 ALTER ADD COLUMN 是为老库升级,新装库由 CREATE TABLE 一次建好,留它会 1060。
-- idx_users_email_verified 同理,已在 schema 中内联。

-- ----------------------------------------------------------------------
-- >>> Source: add_missing_answers_deleted_at.sql
-- ----------------------------------------------------------------------

-- Migration: add_missing_answers_deleted_at.sql
-- Add deleted_at column to answers table if not exists (idempotent)
-- Also adds is_delete if missing, and their indexes
-- Safe to run on both old and new DBs; errors are suppressed via handler

DROP PROCEDURE IF EXISTS add_missing_answers_deleted_at;

DELIMITER //

CREATE PROCEDURE add_missing_answers_deleted_at()
BEGIN
    DECLARE _col_exists INT DEFAULT 0;
    DECLARE _idx_exists INT DEFAULT 0;

    -- Add is_delete if not exists
    SELECT COUNT(*) INTO _col_exists
    FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_SCHEMA = DATABASE()
      AND TABLE_NAME = 'answers'
      AND COLUMN_NAME = 'is_delete';
    IF _col_exists = 0 THEN
        ALTER TABLE answers ADD COLUMN is_delete TINYINT NOT NULL DEFAULT 0 COMMENT 'Logical delete: 0-Not deleted, 1-Deleted' AFTER create_time;
    END IF;

    -- Add deleted_at if not exists
    SELECT COUNT(*) INTO _col_exists
    FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_SCHEMA = DATABASE()
      AND TABLE_NAME = 'answers'
      AND COLUMN_NAME = 'deleted_at';
    IF _col_exists = 0 THEN
        ALTER TABLE answers ADD COLUMN deleted_at TIMESTAMP NULL DEFAULT NULL COMMENT 'Deletion timestamp' AFTER is_delete;
    END IF;

    -- Add idx_answers_is_delete if not exists
    SELECT COUNT(*) INTO _idx_exists
    FROM INFORMATION_SCHEMA.STATISTICS
    WHERE TABLE_SCHEMA = DATABASE()
      AND TABLE_NAME = 'answers'
      AND INDEX_NAME = 'idx_answers_is_delete';
    IF _idx_exists = 0 THEN
        CREATE INDEX idx_answers_is_delete ON answers(is_delete);
    END IF;

    -- Add idx_answers_deleted_at if not exists
    SELECT COUNT(*) INTO _idx_exists
    FROM INFORMATION_SCHEMA.STATISTICS
    WHERE TABLE_SCHEMA = DATABASE()
      AND TABLE_NAME = 'answers'
      AND INDEX_NAME = 'idx_answers_deleted_at';
    IF _idx_exists = 0 THEN
        CREATE INDEX idx_answers_deleted_at ON answers(deleted_at);
    END IF;
END//

DELIMITER ;

CALL add_missing_answers_deleted_at();
DROP PROCEDURE IF EXISTS add_missing_answers_deleted_at;

-- ----------------------------------------------------------------------
-- >>> Source: add_missing_submissions_deleted_at.sql
-- ----------------------------------------------------------------------

-- Migration: add_missing_submissions_deleted_at.sql
-- Add is_delete / deleted_at / answer_id columns to survey_submissions if not exists (idempotent)
-- Also adds their indexes safely

DROP PROCEDURE IF EXISTS add_missing_submissions_deleted_at;

DELIMITER //

CREATE PROCEDURE add_missing_submissions_deleted_at()
BEGIN
    DECLARE _col_exists INT DEFAULT 0;
    DECLARE _idx_exists INT DEFAULT 0;

    -- Add is_delete if not exists
    SELECT COUNT(*) INTO _col_exists
    FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_SCHEMA = DATABASE()
      AND TABLE_NAME = 'survey_submissions'
      AND COLUMN_NAME = 'is_delete';
    IF _col_exists = 0 THEN
        ALTER TABLE survey_submissions ADD COLUMN is_delete TINYINT DEFAULT 0 COMMENT 'Logical delete: 0-not deleted, 1-deleted';
    END IF;

    -- Add deleted_at if not exists
    SELECT COUNT(*) INTO _col_exists
    FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_SCHEMA = DATABASE()
      AND TABLE_NAME = 'survey_submissions'
      AND COLUMN_NAME = 'deleted_at';
    IF _col_exists = 0 THEN
        ALTER TABLE survey_submissions ADD COLUMN deleted_at TIMESTAMP NULL DEFAULT NULL COMMENT 'Deletion timestamp';
    END IF;

    -- Add answer_id if not exists
    SELECT COUNT(*) INTO _col_exists
    FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_SCHEMA = DATABASE()
      AND TABLE_NAME = 'survey_submissions'
      AND COLUMN_NAME = 'answer_id';
    IF _col_exists = 0 THEN
        ALTER TABLE survey_submissions ADD COLUMN answer_id INT COMMENT 'Associated answer ID';
    END IF;

    -- Add idx_submissions_is_delete if not exists
    SELECT COUNT(*) INTO _idx_exists
    FROM INFORMATION_SCHEMA.STATISTICS
    WHERE TABLE_SCHEMA = DATABASE()
      AND TABLE_NAME = 'survey_submissions'
      AND INDEX_NAME = 'idx_submissions_is_delete';
    IF _idx_exists = 0 THEN
        CREATE INDEX idx_submissions_is_delete ON survey_submissions(is_delete);
    END IF;

    -- Add idx_submissions_deleted_at if not exists
    SELECT COUNT(*) INTO _idx_exists
    FROM INFORMATION_SCHEMA.STATISTICS
    WHERE TABLE_SCHEMA = DATABASE()
      AND TABLE_NAME = 'survey_submissions'
      AND INDEX_NAME = 'idx_submissions_deleted_at';
    IF _idx_exists = 0 THEN
        CREATE INDEX idx_submissions_deleted_at ON survey_submissions(deleted_at);
    END IF;

    -- Add idx_submissions_answer_id if not exists
    SELECT COUNT(*) INTO _idx_exists
    FROM INFORMATION_SCHEMA.STATISTICS
    WHERE TABLE_SCHEMA = DATABASE()
      AND TABLE_NAME = 'survey_submissions'
      AND INDEX_NAME = 'idx_submissions_answer_id';
    IF _idx_exists = 0 THEN
        CREATE INDEX idx_submissions_answer_id ON survey_submissions(answer_id);
    END IF;
END//

DELIMITER ;

CALL add_missing_submissions_deleted_at();
DROP PROCEDURE IF EXISTS add_missing_submissions_deleted_at;

-- ----------------------------------------------------------------------
-- >>> Source: add_oauth_bindings_table.sql
-- ----------------------------------------------------------------------

-- OAuth bindings table - tracks user OAuth account binding status
CREATE TABLE IF NOT EXISTS oauth_bindings (
    id INT PRIMARY KEY AUTO_INCREMENT,
    user_id VARCHAR(64) NOT NULL,
    provider VARCHAR(20) NOT NULL COMMENT 'OAuth provider: google, github, microsoft',
    provider_user_id VARCHAR(100) NOT NULL COMMENT 'Provider user ID',
    provider_email VARCHAR(255) NOT NULL COMMENT 'Provider account email',
    provider_username VARCHAR(100) COMMENT 'Provider account username',
    provider_name VARCHAR(100) COMMENT 'Provider account display name',
    provider_avatar VARCHAR(500) COMMENT 'Provider account avatar URL',
    is_primary BOOLEAN DEFAULT FALSE COMMENT 'Whether this is the primary login method',
    binding_method VARCHAR(20) DEFAULT 'manual' COMMENT 'Binding method: manual, auto',
    -- 跨邮箱绑定 / 安全策略相关列,原本在 _migrations/multi_email_oauth_strategy.sql
    -- 单独 ALTER 加,新装库漏跑会 1054。直接建进 CREATE TABLE。
    binding_status VARCHAR(20) NOT NULL DEFAULT 'active' COMMENT 'Binding status: active/pending/suspended',
    verified_at TIMESTAMP NULL DEFAULT NULL COMMENT 'When the binding was verified',
    notes TEXT COMMENT 'Additional notes about the binding',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    UNIQUE KEY unique_provider_user (provider, provider_user_id),
    UNIQUE KEY unique_user_provider (user_id, provider),
    INDEX idx_user_id (user_id),
    INDEX idx_provider (provider),
    INDEX idx_provider_email (provider_email),
    INDEX idx_oauth_bindings_status (binding_status),

    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 跨邮箱绑定的验证 token 表,原本在 _migrations/multi_email_oauth_strategy.sql
-- 单独建,新装库直接建好。
CREATE TABLE IF NOT EXISTS oauth_binding_verifications (
    id INT PRIMARY KEY AUTO_INCREMENT,
    user_id VARCHAR(64) NOT NULL,
    provider VARCHAR(20) NOT NULL,
    provider_email VARCHAR(255) NOT NULL,
    verification_token VARCHAR(64) NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    verified BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_token (verification_token),
    INDEX idx_user_provider (user_id, provider),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 数据回填(从历史 users 推断 provider)只在老库升级时需要,新装库 users 表为空,直接跳过

-- ----------------------------------------------------------------------
-- >>> Source: add_oauth_support_fixed.sql
-- ----------------------------------------------------------------------

-- Add OAuth support database tables
-- Create OAuth account binding table
CREATE TABLE IF NOT EXISTS oauth_accounts (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(64) NOT NULL,
    provider VARCHAR(32) NOT NULL COMMENT 'OAuth provider: google, github, etc.',
    provider_user_id VARCHAR(255) NOT NULL COMMENT 'Third-party platform user ID',
    provider_email VARCHAR(255) NOT NULL COMMENT 'Third-party platform email',
    provider_name VARCHAR(255) COMMENT 'Third-party platform display name',
    created_at DATETIME NOT NULL,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    -- Foreign key constraints
    FOREIGN KEY (username) REFERENCES users(username) ON DELETE CASCADE,

    -- Unique constraint: one third-party account can only bind to one local account
    UNIQUE KEY unique_provider_user (provider, provider_user_id),

    -- Indexes
    INDEX idx_username (username),
    INDEX idx_provider (provider),
    INDEX idx_provider_email (provider_email)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='OAuth account binding table';

-- users 表需要的列(email / display_name / avatar_url)已在 database_schema.sql 中,
-- 此前文件中基于 PREPARE 的 ADD COLUMN 与 MariaDB-only 的 CREATE INDEX IF NOT EXISTS
-- 全部移除,新装库不必再跑。

-- ----------------------------------------------------------------------
-- >>> Source: add_refresh_tokens_table.sql
-- ----------------------------------------------------------------------

-- Create table to persist refresh tokens with rotation support
-- 注意:ENGINE / CHARSET / COLLATE 必须与 users 表保持一致,
-- 否则外键 user_id -> users.id 会因 collation 不匹配被 MySQL 3780 拒绝。
CREATE TABLE IF NOT EXISTS refresh_tokens (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  user_id VARCHAR(64) NOT NULL,
  token_hash VARCHAR(128) NOT NULL,
  issued_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  expires_at DATETIME NOT NULL,
  last_used_at DATETIME NULL,
  user_agent VARCHAR(255) NULL,
  ip_address VARCHAR(64) NULL,
  is_revoked TINYINT(1) NOT NULL DEFAULT 0,
  CONSTRAINT fk_refresh_tokens_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  INDEX idx_user_id_expires (user_id, expires_at),
  INDEX idx_token_hash (token_hash)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ----------------------------------------------------------------------
-- >>> Source: add_users_logical_delete.sql
-- ----------------------------------------------------------------------

-- users.is_delete / deleted_at 及对应索引 idx_users_is_delete / idx_users_deleted_at
-- 已在 database_schema.sql 中内联,此前的 ALTER ADD COLUMN 是为老库升级,
-- 新装库留它会 1060。
